@extends('layouts.app')

@section('title', 'Trip Planner — Routee Surabaya')

@section('content')

<!-- LOADING OVERLAY -->
<div class="trip-loading" id="trip-loading">
    <div class="trip-loading-inner">
        <div class="loading-spinner"></div>
        <h3>Menganalisis Rute...</h3>
        <p>Routee sedang menyusun itinerary terbaik dari titik awalmu</p>
        <div class="loading-steps">
            <div class="ls-item" id="ls-1">✅ Memindai wisata terdekat</div>
            <div class="ls-item" id="ls-2">⏳ Menghitung estimasi waktu & biaya</div>
            <div class="ls-item" id="ls-3">⏳ Menyusun jadwal perjalanan</div>
        </div>
    </div>
</div>

<!-- TRIP CONTENT -->
<div id="trip-content" style="opacity:0;">

    <div class="page-hero page-hero-sm trip-hero">
        <div class="container">
            <span class="section-label">Smart Trip Planner</span>
            <h1>Rencanakan Perjalananmu</h1>
            <p>Pilih dari mana kamu berangkat dan berapa lama waktu yang kamu punya. Kami siapkan rutenya!</p>
        </div>
    </div>

    <section class="section" id="trip-section">
        <div class="container">

            <!-- CONFIGURATION PANEL -->
            <div class="trip-config-panel" style="background: #fff; padding: 2rem; border-radius: 16px; box-shadow: 0 4px 20px rgba(0,0,0,0.05); margin-top: -3rem; position: relative; z-index: 10;">
                <div class="config-group" style="margin-bottom: 1.5rem;">
                    <label style="display:block; font-weight:700; margin-bottom:0.8rem; color:var(--dark);">📍 Titik Keberangkatan</label>
                    <div class="config-options" id="terminal-options" style="display:flex; gap:0.5rem; flex-wrap:wrap;">
                        <button class="config-btn active" data-term="gubeng">Stasiun Gubeng</button>
                        <button class="config-btn" data-term="purabaya">Terminal Purabaya</button>
                        <button class="config-btn" data-term="pasarturi">Stasiun Pasar Turi</button>
                        <button class="config-btn" data-term="wonokromo">Stasiun Wonokromo</button>
                        <button class="config-btn" data-term="joyoboyo">Terminal Joyoboyo</button>
                    </div>
                </div>

                <div class="config-group" style="margin-bottom: 1.5rem;">
                    <label style="display:block; font-weight:700; margin-bottom:0.8rem; color:var(--dark);">⏱️ Durasi Perjalanan</label>
                    <div class="config-options" id="duration-options" style="display:flex; gap:0.5rem; flex-wrap:wrap;">
                        <button class="config-btn" data-hours="4">4 Jam</button>
                        <button class="config-btn active" data-hours="6">6 Jam</button>
                        <button class="config-btn" data-hours="8">8 Jam</button>
                    </div>
                </div>

                <button class="btn btn-primary btn-block btn-lg" id="generate-btn" style="margin-top: 1.5rem; width: 100%;">
                    🚀 Generate Itinerary
                </button>
            </div>

            <!-- CSS for Config panel -->
            <style>
                .config-btn {
                    padding: 0.6rem 1.2rem;
                    border: 1px solid #e2e8f0;
                    border-radius: 30px;
                    background: #fff;
                    color: var(--dark);
                    font-weight: 500;
                    cursor: pointer;
                    transition: all 0.2s;
                }
                .config-btn:hover { background: #f8f9fa; }
                .config-btn.active {
                    background: var(--primary);
                    color: #fff;
                    border-color: var(--primary);
                }
            </style>

            <!-- RESULT AREA -->
            <div id="custom-result-area" style="display: none; margin-top: 3rem;">
                <!-- Generated by JS -->
            </div>

        </div>
    </section>

</div>

@endsection

@section('scripts')
<script>
// Hide loading initially
document.getElementById('trip-loading').style.display = 'none';
document.getElementById('trip-content').style.opacity = '1';

// Toggle active class on config buttons
document.querySelectorAll('#terminal-options .config-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('#terminal-options .config-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
    });
});
document.querySelectorAll('#duration-options .config-btn').forEach(btn => {
    btn.addEventListener('click', function() {
        document.querySelectorAll('#duration-options .config-btn').forEach(b => b.classList.remove('active'));
        this.classList.add('active');
    });
});

// Hardcoded Data for each Terminal
const TERMINAL_DATA = {
    'gubeng': {
        name: 'Stasiun Gubeng',
        transport: ['Ojek Online', 'Suroboyo Bus'],
        spots: [
            { id: 'kalimas', name: 'Monumen Kapal Selam', img: '/images/kapal-selam.jpg', timeLabel: '09:00', dur: '60 menit', price: 15000, dist: '0.5 km dari stasiun' },
            { id: 'alun-alun', name: 'Alun-Alun Surabaya', img: '/images/alun-alun.jpg', timeLabel: '10:30', dur: '45 menit', price: 0, dist: '1 km' },
            { id: 'tunjungan', name: 'Jalan Tunjungan', img: '/images/tunjungan.jpg', timeLabel: '13:30', dur: '60 menit', price: 0, dist: '1.2 km' },
            { id: 'gedung-siola', name: 'Museum Surabaya (Siola)', img: '/images/siola.jpg', timeLabel: '15:00', dur: '60 menit', price: 0, dist: '0.5 km' }
        ],
        food: { name: 'Rujak Cingur Gubeng', img: '/images/rujak.jpeg', price: 30000, dist: 'Dekat area' }
    },
    'purabaya': {
        name: 'Terminal Purabaya (Bungurasih)',
        transport: ['Suroboyo Bus', 'Trans Jatim', 'Ojek Online'],
        spots: [
            { id: 'taman-bungkul', name: 'Taman Bungkul', img: '/images/bungkul.jpg', timeLabel: '09:00', dur: '45 menit', price: 0, dist: '8 km via bus' },
            { id: 'makam-bungkul', name: 'Makam Sunan Bungkul', img: '/images/bungkul.jpg', timeLabel: '10:00', dur: '30 menit', price: 0, dist: '0.1 km' },
            { id: 'alun-alun', name: 'Alun-Alun Surabaya', img: '/images/alun-alun.jpg', timeLabel: '13:30', dur: '60 menit', price: 0, dist: '3 km' },
            { id: 'tunjungan', name: 'Jalan Tunjungan', img: '/images/tunjungan.jpg', timeLabel: '15:00', dur: '60 menit', price: 0, dist: '1 km' }
        ],
        food: { name: 'Rawon Kalkulator', img: '/images/rawon.jpeg', price: 35000, dist: 'Dekat Taman Bungkul' }
    },
    'pasarturi': {
        name: 'Stasiun Pasar Turi',
        transport: ['Ojek Online', 'Angkot'],
        spots: [
            { id: 'maspati', name: 'Kampung Lawas Maspati', img: '/images/maspati.jpg', timeLabel: '09:00', dur: '60 menit', price: 0, dist: '1 km' },
            { id: 'dejavasche', name: 'Gedung De Javasche Bank', img: '/images/dejavasche.jpg', timeLabel: '10:30', dur: '45 menit', price: 5000, dist: '1.5 km' },
            { id: 'kota-lama', name: 'Kawasan Kota Lama', img: '/images/kota-lama.jpg', timeLabel: '13:30', dur: '60 menit', price: 0, dist: '0.5 km' },
            { id: 'ampel', name: 'Makam Sunan Ampel', img: '/images/ampel.jpg', timeLabel: '15:00', dur: '60 menit', price: 0, dist: '2 km' }
        ],
        food: { name: 'Soto Pak Sadi', img: '/images/soto-sadi.jpg', price: 25000, dist: 'Kawasan Peneleh' }
    },
    'wonokromo': {
        name: 'Stasiun Wonokromo',
        transport: ['Suroboyo Bus', 'Ojek Online'],
        spots: [
            { id: 'taman-bungkul', name: 'Taman Bungkul', img: '/images/bungkul.jpg', timeLabel: '09:00', dur: '45 menit', price: 0, dist: '1.5 km' },
            { id: 'alun-alun', name: 'Alun-Alun Surabaya', img: '/images/alun-alun.jpg', timeLabel: '10:30', dur: '60 menit', price: 0, dist: '3 km' },
            { id: 'tunjungan', name: 'Jalan Tunjungan', img: '/images/tunjungan.jpg', timeLabel: '13:30', dur: '60 menit', price: 0, dist: '1 km' },
            { id: 'maspati', name: 'Kampung Lawas Maspati', img: '/images/maspati.jpg', timeLabel: '15:00', dur: '60 menit', price: 0, dist: '2 km' }
        ],
        food: { name: 'Lontong Balap Wonokromo', img: '/images/lontong.jpg', price: 20000, dist: 'Dekat stasiun' }
    },
    'joyoboyo': {
        name: 'Terminal Joyoboyo',
        transport: ['Suroboyo Bus', 'Wira Wiri Suroboyo'],
        spots: [
            { id: 'taman-bungkul', name: 'Taman Bungkul', img: '/images/bungkul.jpg', timeLabel: '09:00', dur: '45 menit', price: 0, dist: '1 km' },
            { id: 'alun-alun', name: 'Alun-Alun Surabaya', img: '/images/alun-alun.jpg', timeLabel: '10:30', dur: '60 menit', price: 0, dist: '3 km' },
            { id: 'tunjungan', name: 'Jalan Tunjungan', img: '/images/tunjungan.jpg', timeLabel: '13:30', dur: '60 menit', price: 0, dist: '1 km' },
            { id: 'kota-lama', name: 'Kawasan Kota Lama', img: '/images/kota-lama.jpg', timeLabel: '15:00', dur: '60 menit', price: 0, dist: '2.5 km' }
        ],
        food: { name: 'Rawon Kalkulator', img: '/images/rawon.jpeg', price: 35000, dist: 'Dekat area' }
    }
};

document.getElementById('generate-btn').addEventListener('click', function() {
    const termId = document.querySelector('#terminal-options .active').dataset.term;
    const hours = parseInt(document.querySelector('#duration-options .active').dataset.hours);
    
    // Show Loading
    const loading = document.getElementById('trip-loading');
    loading.style.display = 'flex';
    loading.style.opacity = '1';
    
    // Reset steps
    document.getElementById('ls-2').textContent = '⏳ Menghitung estimasi waktu & biaya';
    document.getElementById('ls-3').textContent = '⏳ Menyusun jadwal perjalanan';

    setTimeout(() => { document.getElementById('ls-2').textContent = '✅ Menghitung estimasi waktu & biaya'; }, 500);
    setTimeout(() => { document.getElementById('ls-3').textContent = '✅ Menyusun jadwal perjalanan'; }, 1000);

    setTimeout(() => {
        loading.style.opacity = '0';
        setTimeout(() => { loading.style.display = 'none'; renderItinerary(termId, hours); }, 500);
    }, 1500);
});

function renderItinerary(termId, hours) {
    const data = TERMINAL_DATA[termId];
    
    let spotCount = 2; // 4 hours
    if(hours === 6) spotCount = 3;
    if(hours === 8) spotCount = 4;

    const spotsToVisit = data.spots.slice(0, spotCount);
    let totalTicket = spotsToVisit.reduce((sum, spot) => sum + spot.price, 0);
    let totalFood = data.food.price;
    let totalTransport = 20000; // estimated transport budget
    let totalCost = totalTicket + totalFood + totalTransport;

    let html = `
    <div class="trip-layout">
        <div class="trip-timeline-wrap">
            <div class="trip-title-row" style="margin-bottom: 2rem;">
                <h2 class="trip-section-title">📅 Itinerary: ${data.name}</h2>
                <span class="trip-date-badge">Durasi: ${hours} Jam</span>
            </div>

            <div class="timeline" id="trip-timeline">
    `;

    // Render Stops
    spotsToVisit.forEach((spot, idx) => {
        html += `
        <div class="timeline-item">
            <div class="tl-time">
                <span class="tl-hr">${spot.timeLabel}</span>
                <span class="tl-period">WIB</span>
            </div>
            <div class="tl-connector"><div class="tl-dot"></div><div class="tl-line"></div></div>
            <div class="tl-card">
                <div class="tl-card-img">
                    <img src="${spot.img}" alt="${spot.name}" onerror="this.src='/images/placeholder.jpg'">
                </div>
                <div class="tl-card-body">
                    <div class="tl-badge-row">
                        <div class="tl-badge">Stop ${idx + 1}</div>
                    </div>
                    <h3>${spot.name}</h3>
                    <div class="tl-meta">
                        <span>⏱ ${spot.dur}</span>
                        <span>🎟 ${spot.price === 0 ? 'Gratis' : 'Rp ' + spot.price.toLocaleString('id-ID')}</span>
                        <span>📍 Jarak: ${spot.dist}</span>
                    </div>
                </div>
            </div>
        </div>
        `;

        // Insert Lunch & Prayer after Stop 2
        if (idx === 1) {
            html += `
            <div class="timeline-item">
                <div class="tl-time">
                    <span class="tl-hr">12:00</span>
                    <span class="tl-period">WIB</span>
                    <span class="tl-status tl-status-food">Ishoma</span>
                </div>
                <div class="tl-connector"><div class="tl-dot tl-dot-food"></div><div class="tl-line"></div></div>
                <div class="tl-card tl-card-food">
                    <div class="tl-card-body" style="padding: 1rem;">
                        <h3 style="margin: 0 0 0.5rem 0;">🕌 Istirahat & Ibadah</h3>
                        <p style="margin: 0 0 1rem 0; font-size: 0.9rem; color: #666;">Silakan mencari Mushola/Masjid terdekat di area ini untuk menunaikan ibadah.</p>
                        
                        <div style="background: #fff; padding: 1rem; border-radius: 8px; border: 1px solid #eee; display:flex; gap:1rem; align-items:center;">
                            <img src="${data.food.img}" style="width: 60px; height: 60px; border-radius: 8px; object-fit: cover;" onerror="this.src='/images/placeholder.jpg'">
                            <div>
                                <h4 style="margin:0;">🍽️ Rekomendasi Makan Siang: ${data.food.name}</h4>
                                <span style="font-size:0.85rem; color:#666;">Estimasi Biaya: Rp ${data.food.price.toLocaleString('id-ID')}</span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            `;
        }
    });

    html += `
                <div class="tl-end">
                    <div class="tl-end-marker"><span>🏁</span></div>
                    <div class="tl-end-info">
                        <strong>Perjalanan Selesai</strong>
                        <span>Total ${spotsToVisit.length} Destinasi dikunjungi</span>
                    </div>
                </div>
            </div>
        </div>
        
        <!-- SIDEBAR -->
        <div class="trip-sidebar">
            <div class="sidebar-card">
                <div class="sidebar-card-header">
                    <h3>💰 Estimasi Biaya</h3>
                </div>
                <div class="cost-rows">
                    <div class="cost-row"><span>🎟 Tiket Destinasi</span><span>Rp ${totalTicket.toLocaleString('id-ID')}</span></div>
                    <div class="cost-row"><span>🍜 Makan & Minum</span><span>Rp ${totalFood.toLocaleString('id-ID')}</span></div>
                    <div class="cost-row"><span>🛵 Transportasi</span><span>~ Rp ${totalTransport.toLocaleString('id-ID')}</span></div>
                    <div class="cost-divider"></div>
                    <div class="cost-row cost-total"><span>Total</span><span>Rp ${totalCost.toLocaleString('id-ID')}</span></div>
                </div>
            </div>

            <div class="sidebar-card tips-card">
                <h3>💡 Opsi Transportasi dari ${data.name}</h3>
                <ul class="tips-list">
                    ${data.transport.map(t => `<li>✅ ${t}</li>`).join('')}
                </ul>
                <a href="{{ route('transport') }}" class="btn btn-outline btn-block" style="margin-top:1rem;">Selengkapnya tentang Transport</a>
            </div>
        </div>
    </div>
    `;

    const resultArea = document.getElementById('custom-result-area');
    resultArea.innerHTML = html;
    resultArea.style.display = 'block';
    resultArea.scrollIntoView({ behavior: 'smooth', block: 'start' });
}
</script>
@endsection
